name: courir,partir,venir,mourir

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            tag: "linux:pacman"
            pas: "dist/*.pacman"
          - os: "ubuntu-latest"
            tag: "linux:rpm"
            pas: "dist/*.rpm"
          - os: "ubuntu-latest"
            tag: "linux:AppImage"
            pas: "dist/*.AppImage"
          - os: "ubuntu-latest"
            tag: "linux:deb"
            pas: "dist/*.deb"
          - os: "macos-latest"
            tag: "macos"
            pas: "dist/*.dmg"
          - os: "windows-latest"
            tag: "windows"
            pas: "dist/*.exe"
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-tools

      - name: Build!
        shell: bash
        run: |
          pnpm install
          pnpm build:${{ matrix.tag }} --publish never

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ matrix.pas }}
          fail_on_unmatched_files: true
          body: |
            # 📝 更新日志
            - Electron到43.4.1
            ## ⚠️ 最后一版！
            我不会再更新了，因为用的人很少。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize artifact name
        id: fuckname
        shell: bash
        run: echo "name=$(echo '${{ matrix.tag }}' | tr ':' '-')" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.fuckname.outputs.name }}
          path: ${{ matrix.pas }}

  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@main
        with:
          path: ./jure
          merge-multiple: true

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: ./jure/
          remote: /var/www/html/Mineradio/
          key: ${{ secrets.CC_LA_KEY }}
          extra: --delete
